import type {
  AnalyticsPayload,
  DashboardPayload,
  DecisionDetail,
  FarmerProfile,
  FarmerSummary,
  GraphPayload,
  SearchResult,
} from "@/api/types";

export const dashboardPayload: DashboardPayload = {
  welcome: {
    greeting: "Good morning, Kevin",
    subtitle: "Your credit risk overview",
    summary:
      "Portfolio quality remains healthy. Two counties need climate-focused review before approvals are finalized.",
    weatherInsight: "Rift Valley rainfall variance +11% vs seasonal baseline",
    pendingApprovals: 14,
    portfolioHealth: "watch",
    aiJobsToday: 9,
    recentAlerts: 3,
  },
  kpis: [
    {
      id: "pending-reviews",
      label: "Pending reviews",
      value: "14",
      delta: "-3 vs yesterday",
      trend: "down",
      href: "/app/decisions",
    },
    {
      id: "approved-today",
      label: "Approved today",
      value: "28",
      delta: "+6 vs average",
      trend: "up",
      href: "/app/decisions",
    },
    {
      id: "applications",
      label: "Applications in progress",
      value: "186",
      delta: "+22 / 7d",
      trend: "up",
      href: "/app/farmers",
    },
    {
      id: "decision-time",
      label: "Avg decision time",
      value: "4.2h",
      delta: "-18 min",
      trend: "down",
    },
    {
      id: "portfolio-risk",
      label: "Portfolio-at-risk",
      value: "3.1%",
      delta: "-0.4%",
      trend: "down",
      href: "/app/portfolio",
    },
    {
      id: "confidence",
      label: "Recommendation strength",
      value: "Strong",
      delta: "91% avg.",
      trend: "up",
    },
    {
      id: "farmers",
      label: "Borrowers on file",
      value: "18,402",
      delta: "+412 / 30d",
      trend: "up",
      href: "/app/farmers",
    },
    {
      id: "graph-health",
      label: "Profiles fully linked",
      value: "98.4%",
      delta: "Up to date",
      trend: "neutral",
      href: "/app/graph",
    },
  ],
  riskBands: [
    {
      level: "very-low",
      label: "Very low",
      percent: 42,
      farmers: 7733,
      avgLoanKes: 62000,
      approvalRate: 94,
      climateExposure: 12,
    },
    {
      level: "low",
      label: "Low",
      percent: 28,
      farmers: 5153,
      avgLoanKes: 78000,
      approvalRate: 88,
      climateExposure: 18,
    },
    {
      level: "medium",
      label: "Medium",
      percent: 18,
      farmers: 3312,
      avgLoanKes: 94000,
      approvalRate: 72,
      climateExposure: 34,
    },
    {
      level: "high",
      label: "High",
      percent: 9,
      farmers: 1656,
      avgLoanKes: 112000,
      approvalRate: 54,
      climateExposure: 48,
    },
    {
      level: "critical",
      label: "Critical",
      percent: 3,
      farmers: 552,
      avgLoanKes: 128000,
      approvalRate: 31,
      climateExposure: 62,
    },
  ],
  insights: [
    {
      id: "ins-1",
      title: "18 applications ready for fast approval",
      body: "Strong repayment history and complete documentation across the batch.",
      why: "These borrowers match profiles of recently approved loans with low delinquency.",
      icon: "shield",
      severity: "very-low",
    },
    {
      id: "ins-2",
      title: "Nakuru climate pressure rising",
      body: "Rainfall variability is increasing across 8 cooperatives.",
      why: "Current season projection shows extended dry spell risk in two wards.",
      icon: "climate",
      severity: "medium",
    },
    {
      id: "ins-3",
      title: "Duplicate records merged",
      body: "12 previously fragmented records now consolidated into stable borrower profiles.",
      why: "Phone number and supplier links confirmed the same identity.",
      icon: "duplicate",
      severity: "low",
    },
  ],
  activity: [
    {
      id: "act-1",
      timestamp: "09:42",
      type: "loan-approved",
      message: "Officer Mwende approved KES 84,000 for Wanjiru Kamau.",
      actor: "Grace Mwende",
      confidence: 0.94,
      risk: "low",
      farmerId: "farmer-001",
    },
    {
      id: "act-2",
      timestamp: "09:31",
      type: "climate-refresh",
      message: "Rainfall outlook flagged three cooperatives in Nyandarua.",
      actor: "Climate monitoring",
      risk: "medium",
      farmerId: "farmer-002",
    },
    {
      id: "act-3",
      timestamp: "09:14",
      type: "graph-updated",
      message: "Eight borrowers linked to Mwea cluster after profile enrichment.",
      actor: "Data team",
      confidence: 0.89,
      risk: "low",
      farmerId: "farmer-003",
    },
  ],
  quickActions: [
    {
      id: "qa-1",
      label: "Register borrower",
      description: "Add a new farmer profile",
      href: "/app/farmers?create=true",
    },
    {
      id: "qa-2",
      label: "View connections",
      description: "See cooperative and supplier links",
      href: "/app/graph",
    },
    {
      id: "qa-3",
      label: "Review applications",
      description: "Open the pending decision queue",
      href: "/app/decisions",
    },
    {
      id: "qa-4",
      label: "Review pending applications",
      description: "Work through pending decision queue",
      href: "/app/decisions",
    },
  ],
  counties: [
    {
      id: "nakuru",
      name: "Nakuru",
      path: "M 88 118 L 104 112 L 108 128 L 92 134 Z",
      risk: "medium",
      loanVolumeM: 156,
      climateExposure: 41,
      approvalRate: 71,
      farmers: 3420,
      cooperatives: 31,
      applications: 148,
    },
    {
      id: "nyandarua",
      name: "Nyandarua",
      path: "M 78 108 L 92 104 L 96 118 L 82 122 Z",
      risk: "high",
      loanVolumeM: 88,
      climateExposure: 52,
      approvalRate: 68,
      farmers: 1892,
      cooperatives: 14,
      applications: 86,
    },
    {
      id: "meru",
      name: "Meru",
      path: "M 118 88 L 134 84 L 138 100 L 122 104 Z",
      risk: "low",
      loanVolumeM: 124,
      climateExposure: 26,
      approvalRate: 82,
      farmers: 2840,
      cooperatives: 22,
      applications: 102,
    },
    {
      id: "kiambu",
      name: "Kiambu",
      path: "M 108 128 L 118 124 L 122 136 L 112 140 Z",
      risk: "low",
      loanVolumeM: 98,
      climateExposure: 28,
      approvalRate: 84,
      farmers: 2104,
      cooperatives: 24,
      applications: 112,
    },
  ],
};

export const searchResults: SearchResult[] = [
  {
    id: "farmer-001",
    type: "farmer",
    title: "Wanjiru Kamau",
    subtitle: "F001-NAK-2026",
    location: "Nakuru County",
    status: "Application pending",
    risk: "medium",
    href: "/app/farmers/farmer-001",
    recentActivity: "Decision packet updated 20m ago",
  },
  {
    id: "farmer-002",
    type: "farmer",
    title: "Otieno Ouma",
    subtitle: "F002-KIS-2026",
    location: "Kisumu County",
    status: "Approved",
    risk: "low",
    href: "/app/farmers/farmer-002",
    recentActivity: "Repayment event captured",
  },
  {
    id: "decision-041",
    type: "decision",
    title: "Decision D-041",
    subtitle: "Wanjiru Kamau",
    location: "Nakuru Branch",
    status: "Pending review",
    risk: "high",
    href: "/app/decisions/dec-041",
  },
  {
    id: "county-nakuru",
    type: "county",
    title: "Nakuru County",
    subtitle: "Geographic analytics",
    location: "Rift Valley",
    status: "Climate pressure rising",
    risk: "medium",
    href: "/app/analytics?tab=geographic",
  },
];

export const farmerSummaries: FarmerSummary[] = [
  {
    id: "farmer-001",
    farmerId: "F001-NAK-2026",
    name: "Wanjiru Kamau",
    county: "Nakuru",
    cooperative: "Molo Farmers Cooperative",
    cropType: "Potato",
    risk: "medium",
    confidence: 0.91,
    verificationStatus: "verified",
    decisionStatus: "Pending officer review",
    graphConnections: 18,
    climateIndicator: "Rainfall variance +11%",
    lastDecision: "Request info",
    gender: "Female",
    loanAmountKes: 84000,
    applicationStatus: "pending",
  },
  {
    id: "farmer-002",
    farmerId: "F002-KIS-2026",
    name: "Otieno Ouma",
    county: "Kisumu",
    cooperative: "Nyando SACCO",
    cropType: "Maize",
    risk: "low",
    confidence: 0.94,
    verificationStatus: "verified",
    decisionStatus: "Approved",
    graphConnections: 24,
    climateIndicator: "Normalized NDVI trend",
    lastDecision: "Approved",
    gender: "Male",
    loanAmountKes: 62000,
    applicationStatus: "approved",
  },
  {
    id: "farmer-003",
    farmerId: "F003-MER-2026",
    name: "Mary Nkirote",
    county: "Meru",
    cooperative: "Igembe Growers Union",
    cropType: "Tea",
    risk: "high",
    confidence: 0.78,
    verificationStatus: "pending",
    decisionStatus: "Escalated",
    graphConnections: 11,
    climateIndicator: "Drought probability 0.43",
    lastDecision: "Escalated",
    gender: "Female",
    loanAmountKes: 104000,
    applicationStatus: "under_review",
  },
];

export const farmerProfiles: Record<string, FarmerProfile> = {
  "farmer-001": {
    ...farmerSummaries[0],
    phone: "+254 712 000 001",
    parcelHa: 2.4,
    recommendation: "Approve with climate-indexed repayment buffer.",
    officerRecommendation: "Request updated cooperative guarantor list before final approval.",
    dataCompleteness: 91,
    sourceFreshness: "12 minutes ago",
    trustIndicators: [
      "National ID verified",
      "Cooperative membership confirmed",
      "Mobile wallet history linked",
    ],
    contributingFactors: [
      {
        id: "f1",
        label: "Repayment consistency",
        weight: 0.34,
        direction: "positive",
        confidence: 0.94,
        source: "transaction-ledger",
        graphPath: ["farmer", "wallet", "loan-history"],
      },
      {
        id: "f2",
        label: "Climate volatility",
        weight: 0.21,
        direction: "negative",
        confidence: 0.82,
        source: "climate-signals",
        graphPath: ["farmer", "county", "rainfall-anomaly"],
      },
    ],
    repayments: [
      { id: "r1", date: "2026-02-12", amountKes: 12000, onTime: true },
      { id: "r2", date: "2026-03-12", amountKes: 12000, onTime: true },
      { id: "r3", date: "2026-04-12", amountKes: 12000, onTime: true },
      { id: "r4", date: "2026-05-12", amountKes: 8000, onTime: false },
    ],
    loans: [
      { id: "L-1042", amountKes: 68000, status: "closed", termMonths: 8 },
      { id: "L-1133", amountKes: 84000, status: "active", termMonths: 10 },
    ],
    applications: [
      {
        id: "APP-4041",
        amountKes: 84000,
        status: "pending",
        cropType: "Potato",
        submittedAt: "2026-06-21",
      },
    ],
    decisions: [
      {
        id: "dec-041",
        applicationId: "APP-4041",
        recommendation: "approve_with_conditions",
        confidence: 0.91,
        risk: "medium",
        status: "pending",
        createdAt: "2026-06-26",
      },
    ],
    timeline: [
      {
        id: "t1",
        timestamp: "2026-06-26 10:12",
        category: "decision",
        title: "Decision packet generated",
        description: "Model prepared explainable summary for officer review.",
      },
      {
        id: "t2",
        timestamp: "2026-06-25 16:08",
        category: "climate",
        title: "Rainfall anomaly flagged",
        description: "County baseline crossed threshold for seasonal variance.",
      },
    ],
    documents: [
      {
        id: "d1",
        name: "National-ID.pdf",
        type: "identity",
        verificationStatus: "verified",
        uploadedAt: "2026-06-12",
        source: "mobile-upload",
        ocrStatus: "complete",
      },
    ],
    communications: [
      {
        id: "c1",
        channel: "sms",
        message: "Your application is under review.",
        status: "delivered",
        timestamp: "2026-06-26 10:17",
      },
    ],
    climate: {
      rainfallMm: 413,
      droughtProbability: 0.33,
      ndvi: 0.59,
      insight: "Moisture stress likely in two weeks; maintain conservative disbursement.",
      observations: [
        { date: "2026-04", label: "Rainfall", value: "132mm" },
        { date: "2026-05", label: "Rainfall", value: "118mm" },
        { date: "2026-06", label: "Rainfall", value: "163mm" },
      ],
    },
  },
};

export const graphPayload: GraphPayload = {
  nodes: [
    {
      id: "f-001",
      label: "Wanjiru Kamau",
      type: "Farmer",
      risk: "low",
      properties: { county: "Kiambu" },
    },
    {
      id: "coop-f-001",
      label: "Limuru Growers Cooperative",
      type: "Cooperative",
      properties: { county: "Kiambu" },
    },
    {
      id: "loan-f-001",
      label: "Loan 84,000",
      type: "Loan",
      properties: { status: "approved" },
    },
    {
      id: "dealer-f-001",
      label: "Kiambu Input Dealer",
      type: "InputDealer",
      properties: { county: "Kiambu" },
    },
    {
      id: "zone-kiambu",
      label: "Kiambu Climate Zone",
      type: "ClimateZone",
      properties: { droughtProbability: 0.2 },
    },
  ],
  edges: [
    { id: "f-001-e1", source: "f-001", target: "coop-f-001", type: "MEMBER_OF" },
    { id: "f-001-e2", source: "f-001", target: "loan-f-001", type: "OWNS_LOAN" },
    { id: "f-001-e3", source: "f-001", target: "dealer-f-001", type: "PURCHASES_FROM" },
    { id: "f-001-e4", source: "f-001", target: "zone-kiambu", type: "LOCATED_IN" },
    { id: "f-001-e5", source: "coop-f-001", target: "dealer-f-001", type: "WORKS_WITH" },
  ],
};

export const decisionQueue: DecisionDetail[] = [
  {
    id: "dec-041",
    farmerId: "farmer-001",
    farmerName: "Wanjiru Kamau",
    applicationId: "APP-4041",
    recommendation: "approve_with_conditions",
    confidence: 0.91,
    risk: "medium",
    status: "pending",
    factors: farmerProfiles["farmer-001"].contributingFactors,
    positiveSignals: ["Strong repayment consistency", "High cooperative participation"],
    negativeSignals: ["Elevated climate variance", "One late repayment event"],
    officerExplanation: "",
    farmerExplanation:
      "Your record is strong, but weather volatility in your area means the loan may include climate-linked terms.",
    createdAt: "2026-06-26T10:12:00Z",
  },
];

export const analyticsPayload: AnalyticsPayload = {
  executive: {
    totalFarmers: 18402,
    applications: 186,
    approvalRate: 78,
    portfolioHealth: 82,
    avgRisk: 2.3,
    climateExposure: 34,
    avgDecisionHours: 4.2,
    graphCoverage: 98.4,
  },
  lending: [
    { month: "Jan", applications: 152, approved: 112, declined: 40 },
    { month: "Feb", applications: 164, approved: 121, declined: 43 },
    { month: "Mar", applications: 176, approved: 132, declined: 44 },
    { month: "Apr", applications: 170, approved: 126, declined: 44 },
    { month: "May", applications: 181, approved: 137, declined: 44 },
    { month: "Jun", applications: 186, approved: 142, declined: 44 },
  ],
  geographic: dashboardPayload.counties,
  climate: [
    { county: "Nakuru", rainfall: 163, drought: 33, ndvi: 0.59 },
    { county: "Nyandarua", rainfall: 146, drought: 41, ndvi: 0.52 },
    { county: "Meru", rainfall: 174, drought: 22, ndvi: 0.64 },
    { county: "Kiambu", rainfall: 158, drought: 27, ndvi: 0.61 },
  ],
  graph: {
    nodes: 76120,
    relationships: 214004,
    communities: 86,
    avgDegree: 5.6,
    entityResolutionAccuracy: 97.4,
  },
  explainability: {
    avgGenerationSeconds: 2.8,
    topFactors: [
      { factor: "Repayment consistency", count: 362 },
      { factor: "Climate volatility", count: 221 },
      { factor: "Cooperative stability", count: 198 },
    ],
    overrideReasons: [
      { reason: "Seasonal cashflow expectations", count: 24 },
      { reason: "Additional guarantor provided", count: 18 },
      { reason: "Exceptional climate support program", count: 11 },
    ],
  },
};
