/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppFarmersRouteImport } from './routes/app.farmers'
import { Route as AppDecisionsRouteImport } from './routes/app.decisions'
import { Route as AppClimateRouteImport } from './routes/app.climate'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppFarmersIndexRouteImport } from './routes/app.farmers.index'
import { Route as AppDecisionsIndexRouteImport } from './routes/app.decisions.index'
import { Route as AppFarmersFarmerIdRouteImport } from './routes/app.farmers.$farmerId'
import { Route as AppDecisionsDecisionIdRouteImport } from './routes/app.decisions.$decisionId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmersRoute = AppFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppClimateRoute = AppClimateRouteImport.update({
  id: '/climate',
  path: '/climate',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmersIndexRoute = AppFarmersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFarmersRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppFarmersFarmerIdRoute = AppFarmersFarmerIdRouteImport.update({
  id: '/$farmerId',
  path: '/$farmerId',
  getParentRoute: () => AppFarmersRoute,
} as any)
const AppDecisionsDecisionIdRoute = AppDecisionsDecisionIdRouteImport.update({
  id: '/$decisionId',
  path: '/$decisionId',
  getParentRoute: () => AppDecisionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/climate': typeof AppClimateRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/farmers': typeof AppFarmersRouteWithChildren
  '/app/graph': typeof AppGraphRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/farmers/$farmerId': typeof AppFarmersFarmerIdRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
  '/app/farmers/': typeof AppFarmersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/climate': typeof AppClimateRoute
  '/app/graph': typeof AppGraphRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/farmers/$farmerId': typeof AppFarmersFarmerIdRoute
  '/app/decisions': typeof AppDecisionsIndexRoute
  '/app/farmers': typeof AppFarmersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/climate': typeof AppClimateRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/farmers': typeof AppFarmersRouteWithChildren
  '/app/graph': typeof AppGraphRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/farmers/$farmerId': typeof AppFarmersFarmerIdRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
  '/app/farmers/': typeof AppFarmersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/climate'
    | '/app/decisions'
    | '/app/farmers'
    | '/app/graph'
    | '/app/portfolio'
    | '/app/'
    | '/app/decisions/$decisionId'
    | '/app/farmers/$farmerId'
    | '/app/decisions/'
    | '/app/farmers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/climate'
    | '/app/graph'
    | '/app/portfolio'
    | '/app'
    | '/app/decisions/$decisionId'
    | '/app/farmers/$farmerId'
    | '/app/decisions'
    | '/app/farmers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/climate'
    | '/app/decisions'
    | '/app/farmers'
    | '/app/graph'
    | '/app/portfolio'
    | '/app/'
    | '/app/decisions/$decisionId'
    | '/app/farmers/$farmerId'
    | '/app/decisions/'
    | '/app/farmers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farmers': {
      id: '/app/farmers'
      path: '/farmers'
      fullPath: '/app/farmers'
      preLoaderRoute: typeof AppFarmersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/climate': {
      id: '/app/climate'
      path: '/climate'
      fullPath: '/app/climate'
      preLoaderRoute: typeof AppClimateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farmers/': {
      id: '/app/farmers/'
      path: '/'
      fullPath: '/app/farmers/'
      preLoaderRoute: typeof AppFarmersIndexRouteImport
      parentRoute: typeof AppFarmersRoute
    }
    '/app/decisions/': {
      id: '/app/decisions/'
      path: '/'
      fullPath: '/app/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/farmers/$farmerId': {
      id: '/app/farmers/$farmerId'
      path: '/$farmerId'
      fullPath: '/app/farmers/$farmerId'
      preLoaderRoute: typeof AppFarmersFarmerIdRouteImport
      parentRoute: typeof AppFarmersRoute
    }
    '/app/decisions/$decisionId': {
      id: '/app/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/app/decisions/$decisionId'
      preLoaderRoute: typeof AppDecisionsDecisionIdRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
  }
}

interface AppDecisionsRouteChildren {
  AppDecisionsDecisionIdRoute: typeof AppDecisionsDecisionIdRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppDecisionsRouteChildren: AppDecisionsRouteChildren = {
  AppDecisionsDecisionIdRoute: AppDecisionsDecisionIdRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppDecisionsRouteWithChildren = AppDecisionsRoute._addFileChildren(
  AppDecisionsRouteChildren,
)

interface AppFarmersRouteChildren {
  AppFarmersFarmerIdRoute: typeof AppFarmersFarmerIdRoute
  AppFarmersIndexRoute: typeof AppFarmersIndexRoute
}

const AppFarmersRouteChildren: AppFarmersRouteChildren = {
  AppFarmersFarmerIdRoute: AppFarmersFarmerIdRoute,
  AppFarmersIndexRoute: AppFarmersIndexRoute,
}

const AppFarmersRouteWithChildren = AppFarmersRoute._addFileChildren(
  AppFarmersRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClimateRoute: typeof AppClimateRoute
  AppDecisionsRoute: typeof AppDecisionsRouteWithChildren
  AppFarmersRoute: typeof AppFarmersRouteWithChildren
  AppGraphRoute: typeof AppGraphRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClimateRoute: AppClimateRoute,
  AppDecisionsRoute: AppDecisionsRouteWithChildren,
  AppFarmersRoute: AppFarmersRouteWithChildren,
  AppGraphRoute: AppGraphRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
